name: iamsean
favicon: null
layout_spectrum: 0.1287536344025284
typography_spectrum: 0.6409966014325619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b9bbc3'
    - '#585369'
    - '#110a2e'
    - '#f4f2f3'
    - '#b51aae'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
