purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0.5625
  rhythmicContrast: 0.25
  brandColors:
    - '#ffffff'
    - '#1a2127'
    - '#6582a2'
    - '#334b6f'
    - '#a1c8ff'
  lightness: 0.4375
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: iamsean
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.17792
layout_spectrum: 0.2636949
